SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    A.CATEGORY,
    SUM(A.PRICE * B.SALES) AS TOTAL_SALES
FROM (
    SELECT
        A.BOOK_ID,
        A.CATEGORY,
        B.AUTHOR_ID,
        B.AUTHOR_NAME,
        A.PRICE
    FROM BOOK A
    JOIN AUTHOR B
    ON A.AUTHOR_ID = B.AUTHOR_ID
) A
JOIN BOOK_SALES B
ON A.BOOK_ID = B.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, A.CATEGORY
ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC