WITH THR_GEN AS (
    SELECT *
    FROM (SELECT C.ID AS PARENT
        FROM ECOLI_DATA P
        LEFT JOIN ECOLI_DATA C
        ON P.ID = C.PARENT_ID
        WHERE C.ID IS NOT NULL) AS TWO_GEN
    LEFT JOIN ECOLI_DATA THR_GEN
    ON TWO_GEN.PARENT = THR_GEN.PARENT_ID
    WHERE ID IS NOT NULL)
    
SELECT ID FROM THR_GEN
WHERE PARENT_ID NOT IN (SELECT ID FROM THR_GEN)
ORDER BY ID ASC
