SELECT
    ID,
    CASE
    WHEN PERCENT < 0.25 THEN 'CRITICAL'
    WHEN PERCENT < 0.5 AND PERCENT >= 0.25 THEN 'HIGH'
    WHEN PERCENT < 0.75 AND PERCENT >= 0.5 THEN 'MEDIUM'
    ELSE 'LOW'
    END AS COLONY_NAME
FROM
(SELECT
    ID,
    PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PERCENT
FROM ECOLI_DATA) AS A
ORDER BY ID ASC