SELECT 
    REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES,
    ADDRESS,
    ROUND(AVG(RR.REVIEW_SCORE),2) AS SCORE
    FROM REST_INFO RI 
    JOIN REST_REVIEW RR 
    USING (REST_ID)
    WHERE ADDRESS LIKE '서울%'
    GROUP BY RI.REST_ID
    ORDER BY SCORE DESC, FAVORITES DESC