WITH RECURSIVE GENRATION_CTE AS (
    SELECT ID,PARENT_ID,1 AS GENERATION FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT E.ID,E.PARENT_ID, G.GENERATION +1 FROM ECOLI_DATA AS E
    JOIN GENRATION_CTE AS G ON E.PARENT_ID = G.ID
)

SELECT COUNT(GENERATION) AS COUNT ,GENERATION FROM GENRATION_CTE WHERE ID NOT IN (SELECT CTE1.ID FROM GENRATION_CTE AS CTE1 JOIN GENRATION_CTE AS CTE2 ON CTE1.ID = CTE2.PARENT_ID ) GROUP BY GENERATION