SELECT
    CASE
        WHEN MONTH(DIFFERENTIATION_DATE) < 4 AND MONTH(DIFFERENTIATION_DATE) >= 1 THEN '1Q'
        WHEN MONTH(DIFFERENTIATION_DATE) < 7 AND MONTH(DIFFERENTIATION_DATE) >= 4 THEN '2Q'
        WHEN MONTH(DIFFERENTIATION_DATE) < 10 AND MONTH(DIFFERENTIATION_DATE) >= 7 THEN '3Q'
        ELSE '4Q'
    END AS QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER