WITH RECURSIVE TIME AS (
    SELECT 
        0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1
    FROM TIME
    WHERE HOUR < 23
)

SELECT
    A.HOUR,
    COALESCE(B.COUNT, 0) AS COUNT
FROM TIME A
LEFT JOIN (  
    SELECT 
        HOUR(DATETIME) AS HOUR, 
        COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
) B
ON A.HOUR = B.HOUR
ORDER BY HOUR

