SELECT
    ID,
    EMAIL,
    FIRST_NAME,
    LAST_NAME
FROM DEVELOPERS A
JOIN (
        SELECT 
            SUM(CODE) AS FRONT_END_CODE
        FROM SKILLCODES
        WHERE CATEGORY = 'Front End') B
WHERE A.SKILL_CODE & B.FRONT_END_CODE > 0
ORDER BY ID
