SELECT 
    A.EMP_NO,
    A.EMP_NAME,
    B.GRADE,
    CASE
        WHEN B.GRADE = 'S' THEN SAL*0.2
        WHEN B.GRADE = 'A' THEN SAL*0.15
        WHEN B.GRADE = 'B' THEN SAL*0.1
        ELSE 0
        END AS BONUS
FROM HR_EMPLOYEES A
JOIN (SELECT
    A.EMP_NO,
    A.EMP_NAME,
    CASE 
        WHEN AVG(SCORE) >= 96 THEN 'S'
        WHEN AVG(SCORE) >= 90 THEN 'A'
        WHEN AVG(SCORE) >= 80 THEN 'B'
        ELSE 'C'
        END AS GRADE
    FROM HR_EMPLOYEES A
    JOIN HR_GRADE B
    ON A.EMP_NO = B.EMP_NO
    GROUP BY EMP_NO, EMP_NAME) AS B
ON A.EMP_NO = B.EMP_NO
ORDER BY EMP_NO
