WITH REVIEWS AS (
SELECT
    MEMBER_ID,
    COUNT(*) AS TOTAL_REVIEW
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY TOTAL_REVIEW DESC
)

SELECT 
    A.MEMBER_NAME,
    B.REVIEW_TEXT,
    DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE A
JOIN (
    SELECT * 
    FROM REST_REVIEW
    WHERE MEMBER_ID IN (
        SELECT MEMBER_ID
        FROM REVIEWS
        WHERE TOTAL_REVIEW = (SELECT TOTAL_REVIEW  FROM REVIEWS LIMIT 1))
) B
ON A.MEMBER_ID = B.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT

