SELECT 
    MCDP_CD AS 진료과코드,
    COUNT(*) AS 5월예약건수
FROM (
        SELECT * 
        FROM APPOINTMENT
        WHERE YEAR(APNT_YMD) = 2022 AND MONTH(APNT_YMD) = 5) AS A
GROUP BY MCDP_CD
ORDER BY 5월예약건수 ASC, 진료과코드 ASC