WITH A AS (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
),
B AS (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR, 
        SIZE_OF_COLONY, 
        ID
    FROM ECOLI_DATA
)

SELECT 
    B.YEAR AS YEAR,
    (A.MAX_SIZE-B.SIZE_OF_COLONY) AS YEAR_DEV,
    B.ID
FROM A
JOIN B
ON A.YEAR = B.YEAR
ORDER BY YEAR, YEAR_DEV