SELECT 
    INGREDIENT_TYPE,
    SUM(TOTAL_ORDER) AS TOTAL_ORDER 
FROM (SELECT A.FLAVOR, TOTAL_ORDER, INGREDIENT_TYPE
FROM FIRST_HALF A
JOIN ICECREAM_INFO B
ON A.FLAVOR = B.FLAVOR) AS C
GROUP BY INGREDIENT_TYPE


