SELECT 
    TITLE,
    BOARD_ID, 
    REPLY_ID, 
    UGR.WRITER_ID, 
    UGR.CONTENTS, 
    DATE_FORMAT(UGR.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE

FROM USED_GOODS_BOARD UGB
INNER JOIN USED_GOODS_REPLY UGR
USING (BOARD_ID)
WHERE UGB.CREATED_DATE LIKE '2022-10%'
ORDER BY UGR.CREATED_DATE ASC, TITLE ASC