SELECT 
    COUNT(*) AS FISH_COUNT,
    MAX(LENGTH) AS MAX_LENGTH,
    A.FISH_TYPE
FROM FISH_INFO AS A
JOIN (
    SELECT 
    FISH_TYPE,
    AVG(LENGTH) AS AVG_LEN
FROM (
        SELECT
        ID,
        FISH_TYPE,
        CASE
            WHEN LENGTH <= 10 THEN 10
            ELSE LENGTH
        END AS LENGTH,
        TIME
    FROM FISH_INFO
) AS C
GROUP BY FISH_TYPE
HAVING AVG_LEN >= 33
) AS B
ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY A.FISH_TYPE
ORDER BY A.FISH_TYPE ASC


